// Package web holds the built frontend bundle.
//
// The bundle is embedded rather than read from disk so the binary is the whole
// deployment - the same reason migrations are embedded. A container image ships
// one file, not a file plus a directory that has to stay beside it.
//
// dist/ is generated by scripts/build-frontend.sh and is not committed, so a
// fresh clone embeds only .gitkeep. The server detects that and serves an
// explanatory page instead of a blank 404.
package web

import "embed"

// Dist holds the built frontend. The all: prefix is required: without it the
// directive below skips dotfiles, and on a fresh clone .gitkeep is the only
// file here - an empty match is a compile error.
//
//go:embed all:dist
var Dist embed.FS
